# Generated by Django 5.1.3 on 2024-11-28 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0004_alter_producttask_options_product_short_12v_48v_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_detail', to='product_management.product'),
        ),
        migrations.AlterField(
            model_name='location',
            name='layer_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='rack_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='space_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
