# Generated by Django 5.1.3 on 2024-12-02 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0005_location_product_alter_location_layer_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='action',
            new_name='task_name',
        ),
    ]
