# Generated by Django 5.1.3 on 2024-12-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_management", "0006_rename_action_task_task_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statustask",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
