# Generated by Django 5.1.3 on 2024-12-10 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0009_category_created_category_modified_location_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_removed',
        ),
    ]
